# DSC 450 Project 1: NOAA Storm Event Data Wrangling

**Project:** Predicting Extreme Weather Severity Using NOAA Storm Records
**Dataset:** NOAA Storm Event Database, 2020-2025
**Purpose:** Data exploration, cleaning, transformation and feature engineering

### Project Goal
This notebook documents the exploration, cleaning, transformation and feature engineering performed on the NOAA Storm Events dataset for Project 1. The final dataset will be prepared for the project's predictive modeling tasks, including classification of storm event severity.

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np

## 2. Load the Dataset

The NOAA Storm Events dataset for 2020-2025 will be loaded into a pandas DataFrame for exploration and data wrangling.

In [2]:
df = pd.read_csv('noaa_storm_events_2020_2025.csv')

## 3. Dataset Overview

The dataset will be examined to understand the structure, dimensions, variables, and data types.

In [3]:
df.shape

(410311, 52)

In [4]:
df.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE,SOURCE_YEAR
0,202006,24,1620,202006,24,1620,149684,902190,GEORGIA,13,...,W,DOLES,31.7000,-83.8900,31.7000,-83.8900,"As is typical during summer, scattered afterno...",A power line was blown down on Highway 32W. H...,CSV,2020
1,202006,20,1930,202006,20,1930,149048,898391,KANSAS,20,...,SE,CALVERT,39.7571,-99.6684,39.7571,-99.6684,Supercells in small clusters formed during the...,Penny to quarter size hail reported and ongoin...,CSV,2020
2,202006,3,1550,202006,3,1550,149149,899120,KANSAS,20,...,NW,ST FRANCIS,39.9137,-101.9753,39.9137,-101.9753,Thunderstorms formed in eastern Colorado durin...,Dime to penny sized hail reported at the locat...,CSV,2020
3,202006,19,1900,202006,19,1900,149046,898383,KANSAS,20,...,SSE,BREWSTER,39.3400,-101.3700,39.3400,-101.3700,Thunderstorms moved east off the central Rocki...,Officer reported an estimated 60 mph wind gust...,CSV,2020
4,202006,20,1900,202006,20,1900,149048,898388,KANSAS,20,...,SE,NORTON MUNI ARPT,39.8400,-99.8900,39.8400,-99.8900,Supercells in small clusters formed during the...,NaN,CSV,2020

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410311 entries, 0 to 410310
Data columns (total 52 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   BEGIN_YEARMONTH     410311 non-null  int64
 1   BEGIN_DAY           410311 non-null  int64
 2   BEGIN_TIME          410311 non-null  int64
 3   END_YEARMONTH       410311 non-null  int64
 4   END_DAY             410311 non-null  int64
 5   END_TIME            410311 non-null  int64
 6   EPISODE_ID          410311 non-null  int64
 7   EVENT_ID            410311 non-null  int64
 8   STATE               410311 non-null  object
 9   STATE_FIPS          410311 non-null  int64
 10  YEAR                410311 non-null  int64
 11  MONTH_NAME          410311 non-null  object
 12  EVENT_TYPE          410311 non-null  object
 13  CZ_TYPE             410311 non-null  object
 14  CZ_FIPS             410311 non-null  int64
 15  CZ_NAME             410311 non-null  object
 16  WFO                 410311 non-null  object
 17  BEGIN_DATE_TIME     410311 non-null  object
 18  CZ_TIMEZONE         410311 non-null  object
 19  END_DATE_TIME       410311 non-null  object
 20  INJURIES_DIRECT     410311 non-null  int64
 21  INJURIES_INDIRECT   410311 non-null  int64
 22  DEATHS_DIRECT       410311 non-null  int64
 23  DEATHS_INDIRECT     410311 non-null  int64
 24  DAMAGE_PROPERTY     319237 non-null  object
 25  DAMAGE_CROPS        319011 non-null  object
 26  SOURCE              410311 non-null  object
 27  MAGNITUDE           214407 non-null  float64
 28  MAGNITUDE_TYPE      163224 non-null  object
 29  FLOOD_CAUSE         40399 non-null   object
 30  CATEGORY            217 non-null     float64
 31  TOR_F_SCALE         9432 non-null    object
 32  TOR_LENGTH          9432 non-null    float64
 33  TOR_WIDTH           9432 non-null    float64
 34  TOR_OTHER_WFO       1441 non-null    object
 35  TOR_OTHER_CZ_STATE  1441 non-null    object
 36  TOR_OTHER_CZ_FIPS   1441 non-null    float64
 37  TOR_OTHER_CZ_NAME   1441 non-null    object
 38  BEGIN_RANGE         242317 non-null  float64
 39  BEGIN_AZIMUTH       242289 non-null  object
 40  BEGIN_LOCATION      242289 non-null  object
 41  END_RANGE           242317 non-null  float64
 42  END_AZIMUTH         242289 non-null  object
 43  END_LOCATION        242289 non-null  object
 44  BEGIN_LAT           242289 non-null  float64
 45  BEGIN_LON           242289 non-null  float64
 46  END_LAT             242289 non-null  float64
 47  END_LON             242289 non-null  float64
 48  EPISODE_NARRATIVE   410311 non-null  object
 49  EVENT_NARRATIVE     338423 non-null  object
 50  DATA_SOURCE         410311 non-null  object
 51  SOURCE_YEAR         410311 non-null  int64
dtypes: float64(11), int64(16), object(25)
memory usage: 162.8+ MB

## 4. Variable Exploration

This section will examine the variables inclued in the NOAA Storm Events dataset.

In [6]:
df.dtypes

BEGIN_YEARMONTH         int64
BEGIN_DAY               int64
BEGIN_TIME              int64
END_YEARMONTH           int64
END_DAY                 int64
END_TIME                int64
EPISODE_ID              int64
EVENT_ID                int64
STATE                  object
STATE_FIPS              int64
YEAR                    int64
MONTH_NAME             object
EVENT_TYPE             object
CZ_TYPE                object
CZ_FIPS                 int64
CZ_NAME                object
WFO                    object
BEGIN_DATE_TIME        object
CZ_TIMEZONE            object
END_DATE_TIME          object
INJURIES_DIRECT         int64
INJURIES_INDIRECT       int64
DEATHS_DIRECT           int64
DEATHS_INDIRECT         int64
DAMAGE_PROPERTY        object
DAMAGE_CROPS           object
SOURCE                 object
MAGNITUDE             float64
MAGNITUDE_TYPE         object
FLOOD_CAUSE            object
CATEGORY              float64
TOR_F_SCALE            object
TOR_LENGTH            float64
TOR_WIDTH             float64
TOR_OTHER_WFO          object
TOR_OTHER_CZ_STATE     object
TOR_OTHER_CZ_FIPS     float64
TOR_OTHER_CZ_NAME      object
BEGIN_RANGE           float64
BEGIN_AZIMUTH          object
BEGIN_LOCATION         object
END_RANGE             float64
END_AZIMUTH            object
END_LOCATION           object
BEGIN_LAT             float64
BEGIN_LON             float64
END_LAT               float64
END_LON               float64
EPISODE_NARRATIVE      object
EVENT_NARRATIVE        object
DATA_SOURCE            object
SOURCE_YEAR             int64
dtype: object

In [7]:
df["EVENT_TYPE"].nunique()

54

In [8]:
df["STATE"].value_counts()

STATE
TEXAS             33173
OKLAHOMA          15191
CALIFORNIA        14905
KANSAS            13574
ILLINOIS          13330
                  ...
E PACIFIC            17
ST LAWRENCE R        12
GULF OF ALASKA       12
HAWAII WATERS         3
GUAM WATERS           3
Name: count, Length: 69, dtype: int64

In [9]:
df["MAGNITUDE_TYPE"].value_counts()

MAGNITUDE_TYPE
EG    103581
MG     58169
MS      1369
ES       105
Name: count, dtype: int64

In [10]:
df["TOR_F_SCALE"].value_counts()

TOR_F_SCALE
EF1    3613
EF0    3343
EFU    1312
EF2     913
EF3     213
EF4      37
EF5       1
Name: count, dtype: int64

In [11]:
df["CATEGORY"].value_counts(dropna=False)

CATEGORY
NaN    410094
1.0       123
2.0        56
3.0        20
4.0        18
Name: count, dtype: int64

In [12]:
df["STATE_FIPS"].value_counts().sort_index()

STATE_FIPS
1      9269
2      1818
4      6132
5      7778
6     14905
      ...
95      618
96       67
97      214
98      189
99     2183
Name: count, Length: 69, dtype: int64

In [13]:
df["DAMAGE_PROPERTY"].value_counts(dropna=False).head(20)

DAMAGE_PROPERTY
0.00K      241476
NaN         91074
1.00K       14654
5.00K        8510
2.00K        7806
10.00K       7129
3.00K        4614
0.50K        3695
50.00K       2864
20.00K       2858
25.00K       2466
15.00K       2255
100.00K      1866
4.00K        1551
30.00K       1194
1.50K         862
8.00K         722
250.00K       665
0.20K         655
6.00K         648
Name: count, dtype: int64

In [14]:
df["DAMAGE_CROPS"].value_counts(dropna=False).head(20)

DAMAGE_CROPS
0.00K      313736
NaN         91300
1.00K        1329
2.00K         355
5.00K         300
0.10K         274
3.00K         260
10.00K        246
0.01K         136
0.50K         134
500.00K       129
1.00M         120
0             119
50.00K        112
20.00K         71
4.00K          67
100.00K        64
15.00K         61
25.00K         42
2.00M          41
Name: count, dtype: int64

## 5. Missing Value Exploration

In [15]:
df.isnull().sum()

BEGIN_YEARMONTH            0
BEGIN_DAY                  0
BEGIN_TIME                 0
END_YEARMONTH              0
END_DAY                    0
END_TIME                   0
EPISODE_ID                 0
EVENT_ID                   0
STATE                      0
STATE_FIPS                 0
YEAR                       0
MONTH_NAME                 0
EVENT_TYPE                 0
CZ_TYPE                    0
CZ_FIPS                    0
CZ_NAME                    0
WFO                        0
BEGIN_DATE_TIME            0
CZ_TIMEZONE                0
END_DATE_TIME              0
INJURIES_DIRECT            0
INJURIES_INDIRECT          0
DEATHS_DIRECT              0
DEATHS_INDIRECT            0
DAMAGE_PROPERTY        91074
DAMAGE_CROPS           91300
SOURCE                     0
MAGNITUDE             195904
MAGNITUDE_TYPE        247087
FLOOD_CAUSE           369912
CATEGORY              410094
TOR_F_SCALE           400879
TOR_LENGTH            400879
TOR_WIDTH             400879
TOR_OTHER_WFO         408870
TOR_OTHER_CZ_STATE    408870
TOR_OTHER_CZ_FIPS     408870
TOR_OTHER_CZ_NAME     408870
BEGIN_RANGE           167994
BEGIN_AZIMUTH         168022
BEGIN_LOCATION        168022
END_RANGE             167994
END_AZIMUTH           168022
END_LOCATION          168022
BEGIN_LAT             168022
BEGIN_LON             168022
END_LAT               168022
END_LON               168022
EPISODE_NARRATIVE          0
EVENT_NARRATIVE        71888
DATA_SOURCE                0
SOURCE_YEAR                0
dtype: int64

In [16]:
pd.crosstab(df["EVENT_TYPE"], df["MAGNITUDE_TYPE"])

MAGNITUDE_TYPE               EG  ES     MG    MS
EVENT_TYPE
High Wind                  3539  65  20633  1311
Marine High Wind             20   0    437     6
Marine Strong Wind            8   2     15     0
Marine Thunderstorm Wind   1544  15  13547     5
Strong Wind                3950  14   2642    44
Thunderstorm Wind         94520   9  20895     3

In [17]:
pd.crosstab(
    df["MAGNITUDE"].notna(),
    df["MAGNITUDE_TYPE"].notna()
)

MAGNITUDE_TYPE   False   True
MAGNITUDE
False           195904       0
True             51183  163224

In [18]:
pd.crosstab(
    df["EVENT_TYPE"],
    df["FLOOD_CAUSE"].notna()
)

FLOOD_CAUSE                  False  True
EVENT_TYPE
Astronomical Low Tide          164      0
Avalanche                      200      0
Blizzard                      2955      0
Coastal Flood                 1469      0
Cold/Wind Chill               3794      0
Debris Flow                      0    982
Dense Fog                     4105      0
Dense Smoke                     63      0
Drought                      25771      0
Dust Devil                      27      0
Dust Storm                     926      0
Excessive Heat               12370      0
Extreme Cold/Wind Chill       5892      0
Flash Flood                      0  25142
Flood                            0  14275
Freezing Fog                    76      0
Frost/Freeze                  3084      0
Funnel Cloud                  1327      0
Hail                         51036      0
Heat                         13744      0
Heavy Rain                    6284      0
Heavy Snow                   12900      0
High Surf                     1422      0
High Wind                    25548      0
Hurricane (Typhoon)            217      0
Ice Storm                     1344      0
Lake-Effect Snow               519      0
Lakeshore Flood                165      0
Lightning                     1493      0
Marine Dense Fog                14      0
Marine Hail                    147      0
Marine High Wind               463      0
Marine Hurricane/Typhoon        59      0
Marine Lightning                 1      0
Marine Strong Wind              25      0
Marine Thunderstorm Wind     15111      0
Marine Tropical Depression      20      0
Marine Tropical Storm          433      0
Rip Current                    545      0
Seiche                          11      0
Sleet                          131      0
Sneakerwave                     44      0
Storm Surge/Tide               329      0
Strong Wind                   6650      0
Thunderstorm Wind           115427      0
Tornado                       9432      0
Tropical Depression            143      0
Tropical Storm                2000      0
Tsunami                         19      0
Volcanic Ashfall                 8      0
Waterspout                    1145      0
Wildfire                      2169      0
Winter Storm                 16221      0
Winter Weather               22470      0

### Observations

Further examination of missing values will take place after research question is solidified. At this time, no cleaning will be performed for missing values.

## 6. Duplicate Records Assessment

In [19]:
df.duplicated().sum()

np.int64(0)

### Observations

There are no duplicate records in this dataset.

## 7. Numeric Variable Exploration

Numerical values will be examined to identify unusual values, unexpected ranges, and potential data-quality issues.

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
BEGIN_YEARMONTH,410311.0,2.022665e+05,168.094841,202001.0000,202108.0000,2.023030e+05,2.024060e+05,2.025120e+05
BEGIN_DAY,410311.0,1.471507e+01,9.017404,1.0000,7.0000,1.400000e+01,2.200000e+01,3.100000e+01
BEGIN_TIME,410311.0,1.243377e+03,679.972692,0.0000,732.0000,1.412000e+03,1.756000e+03,2.359000e+03
END_YEARMONTH,410311.0,2.022665e+05,168.094841,202001.0000,202108.0000,2.023030e+05,2.024060e+05,2.025120e+05
END_DAY,410311.0,1.666822e+01,9.046782,1.0000,9.0000,1.600000e+01,2.500000e+01,3.100000e+01
END_TIME,410311.0,1.478590e+03,615.890413,0.0000,1100.0000,1.613000e+03,1.905000e+03,2.359000e+03
EPISODE_ID,410311.0,1.773301e+05,18491.725845,143808.0000,161538.0000,1.780500e+05,1.929540e+05,2.101610e+05
EVENT_ID,410311.0,1.085272e+06,125781.413117,863438.0000,976727.5000,1.084577e+06,1.193646e+06,1.310672e+06
STATE_FIPS,410311.0,3.319064e+01,19.651635,1.0000,19.0000,3.100000e+01,4.700000e+01,9.900000e+01
YEAR,410311.0,2.022605e+03,1.683046,2020.0000,2021.0000,2.023000e+03,2.024000e+03,2.025000e+03
CZ_FIPS,410311.0,1.122508e+02,139.884123,1.0000,27.0000,6.700000e+01,1.290000e+02,8.760000e+02
INJURIES_DIRECT,410311.0,2.417922e-02,1.812346,0.0000,0.0000,0.000000e+00,0.000000e+00,8.060000e+02
INJURIES_INDIRECT,410311.0,5.583570e-03,0.336217,0.0000,0.0000,0.000000e+00,0.000000e+00,1.000000e+02
DEATHS_DIRECT,410311.0,1.236867e-02,0.398910,0.0000,0.0000,0.000000e+00,0.000000e+00,1.020000e+02
DEATHS_INDIRECT,410311.0,4.372293e-03,0.164063,0.0000,0.0000,0.000000e+00,0.000000e+00,5.600000e+01
MAGNITUDE,214407.0,4.008301e+01,22.972887,0.1300,34.0000,5.000000e+01,5.400000e+01,1.440000e+02
CATEGORY,217.0,1.691244e+00,0.948472,1.0000,1.0000,1.000000e+00,2.000000e+00,4.000000e+00
TOR_LENGTH,9432.0,3.607532e+00,4.545782,0.0100,0.6200,2.000000e+00,4.802500e+00,4.996000e+01
TOR_WIDTH,9432.0,2.102262e+02,312.782380,1.0000,50.0000,1.000000e+02,2.500000e+02,3.960000e+03
TOR_OTHER_CZ_FIPS,1441.0,1.010701e+02,80.894109,1.0000,43.0000,8.900000e+01,1.350000e+02,8.200000e+02
BEGIN_RANGE,242317.0,2.360092e+00,4.300244,0.0000,0.6900,1.380000e+00,2.710000e+00,1.988900e+02
END_RANGE,242317.0,2.371915e+00,4.301460,0.0000,0.6900,1.380000e+00,2.710000e+00,1.990300e+02
BEGIN_LAT,242289.0,3.755063e+01,5.269846,-14.3477,34.1900,3.803000e+01,4.115240e+01,7.036790e+01
BEGIN_LON,242289.0,-8.971184e+01,11.774849,-170.8744,-97.0477,-8.849450e+01,-8.109870e+01,1.714689e+02
END_LAT,242289.0,3.755054e+01,5.270697,-14.3491,34.1905,3.803000e+01,4.115270e+01,7.027890e+01
END_LON,242289.0,-8.970670e+01,11.773958,-170.8326,-97.0446,-8.848030e+01,-8.109000e+01,1.714689e+02
SOURCE_YEAR,410311.0,2.022605e+03,1.683046,2020.0000,2021.0000,2.023000e+03,2.024000e+03,2.025000e+03

### Observations

The NOAA codebook was used to validate latitude, longitude and range variables. No impossible values were identified. Several features need to be converted to other data types, like CATEGORY and multiple features that need to be datetime objects. Further examination will occur before converting those features.

## 8. Date/Time Validation and Conversion

In [21]:
df[['BEGIN_DATE_TIME', 'END_DATE_TIME']].head(10)

      BEGIN_DATE_TIME       END_DATE_TIME
0  24-JUN-20 16:20:00  24-JUN-20 16:20:00
1  20-JUN-20 19:30:00  20-JUN-20 19:30:00
2  03-JUN-20 15:50:00  03-JUN-20 15:50:00
3  19-JUN-20 19:00:00  19-JUN-20 19:00:00
4  20-JUN-20 19:00:00  20-JUN-20 19:00:00
5  20-JUN-20 18:37:00  20-JUN-20 18:37:00
6  23-JUN-20 15:11:00  23-JUN-20 15:11:00
7  26-JUN-20 18:30:00  26-JUN-20 18:30:00
8  26-JUN-20 18:45:00  26-JUN-20 18:50:00
9  09-JUN-20 13:44:00  09-JUN-20 13:44:00

In [22]:
df["BEGIN_DATE_TIME"].min(), df["BEGIN_DATE_TIME"].max()

('01-APR-20 00:00:00', '31-OCT-25 19:00:00')

In [23]:
df["END_DATE_TIME"].min(), df["END_DATE_TIME"].max()

('01-APR-20 04:55:00', '31-OCT-25 23:59:00')

In [24]:
df["BEGIN_DATE_TIME"] = pd.to_datetime(
    df["BEGIN_DATE_TIME"],
    format="%d-%b-%y %H:%M:%S"
)

df["END_DATE_TIME"] = pd.to_datetime(
    df["END_DATE_TIME"],
    format="%d-%b-%y %H:%M:%S"
)

In [25]:
# Validate dtype change
df[["BEGIN_DATE_TIME", "END_DATE_TIME"]].dtypes

BEGIN_DATE_TIME    datetime64[ns]
END_DATE_TIME      datetime64[ns]
dtype: object

In [26]:
(df["END_DATE_TIME"] < df["BEGIN_DATE_TIME"]).sum()

np.int64(0)

## 9. Data Cleaning

The raw dataset will be preserved. A new copy will be created for all cleaning changes.

In [27]:
df_clean = df.copy()

### Damage Values

DAMAGE_PROPERTY and DAMAGE_CROPS are currently stored as text. They need to be converted to numeric dollar amounts.

In [28]:
df_clean["DAMAGE_PROPERTY"].dropna().str[-1].value_counts()

DAMAGE_PROPERTY
K    316963
M      2134
0       119
B        21
Name: count, dtype: int64

In [29]:
df_clean["DAMAGE_CROPS"].dropna().str[-1].value_counts()

DAMAGE_CROPS
K    318308
M       584
0       119
Name: count, dtype: int64

In [30]:
def convert_damage(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip()

    if value.endswith("K"):
        return float(value[:-1]) * 1_000
    elif value.endswith("M"):
        return float(value[:-1]) * 1_000_000
    elif value.endswith("B"):
        return float(value[:-1]) * 1_000_000_000
    else:
        return float(value)

In [31]:
df_clean["DAMAGE_PROPERTY"] = df_clean["DAMAGE_PROPERTY"].apply(convert_damage)
df_clean["DAMAGE_CROPS"] = df_clean["DAMAGE_CROPS"].apply(convert_damage)

In [45]:
df_clean = df_clean.rename(columns={
    "DAMAGE_PROPERTY": "PROPERTY_DAMAGE_USD",
    "DAMAGE_CROPS": "CROP_DAMAGE_USD"
})
df_clean[["PROPERTY_DAMAGE_USD", "CROP_DAMAGE_USD"]].dtypes

PROPERTY_DAMAGE_USD    float64
CROP_DAMAGE_USD        float64
dtype: object

In [47]:
df_clean[["PROPERTY_DAMAGE_USD", "CROP_DAMAGE_USD"]].isna().sum()

PROPERTY_DAMAGE_USD    91074
CROP_DAMAGE_USD        91300
dtype: int64

### Magnitude Data Cleaning

In [34]:
magnitude_type_missing = (
    df_clean["MAGNITUDE"].notna() &
    df_clean["MAGNITUDE_TYPE"].isna()
)

magnitude_type_missing.sum()

np.int64(51183)

In [35]:
df_clean.loc[
    magnitude_type_missing,
    "EVENT_TYPE"
].value_counts()

EVENT_TYPE
Hail           51036
Marine Hail      147
Name: count, dtype: int64

#### Observations

Missing values are due to event type. Nothing will be filled in for the null values at this time.

## 10. Data Quality Validation

The cleaned dataset will be reviewed to confirm that cleaning produced consistent and analysis ready data.

In [48]:
print("Dataset shape:", df_clean.shape)
print("Duplicate rows:", df_clean.duplicated().sum())
print("Duplicate EVENT_IDs:", df_clean["EVENT_ID"].duplicated().sum())
print("End before begin:", (df_clean["END_DATE_TIME"] < df_clean["BEGIN_DATE_TIME"]).sum())
print("Negative property damage:", (df_clean["PROPERTY_DAMAGE_USD"] < 0).sum())
print("Negative crop damage:", (df_clean["CROP_DAMAGE_USD"] < 0).sum())

Dataset shape: (410311, 54)
Duplicate rows: 0
Duplicate EVENT_IDs: 0
End before begin: 0
Negative property damage: 0
Negative crop damage: 0

## 10. Feature Engineering

New variables will be created from the cleaned dataset based on the project's research questions and modeling requirements.

### Storm Duration

Caluculated using beginning and end date/time of each event. 

Can be used as a potential predictor.

In [38]:
df_clean['STORM_DURATION_HOURS'] = (
    df_clean['END_DATE_TIME'] - df_clean['BEGIN_DATE_TIME']).dt.total_seconds() / 3600

In [39]:
df_clean["STORM_DURATION_HOURS"].describe()

count    410311.000000
mean         49.251132
std         161.651861
min           0.000000
25%           0.000000
50%           0.166667
75%          11.000000
max         743.983333
Name: STORM_DURATION_HOURS, dtype: float64

### Season

In [40]:
df_clean['SEASON'] = df_clean['BEGIN_DATE_TIME'].dt.month.map({
    12: "Winter",
    1: "Winter",
    2: "Winter",
    3: "Spring",
    4: "Spring",
    5: "Spring",
    6: "Summer",
    7: "Summer",
    8: "Summer",
    9: "Fall",
    10: "Fall",
    11: "Fall"
})

In [41]:
df_clean["SEASON"].value_counts()

SEASON
Summer    156986
Spring    111642
Winter     92555
Fall       49128
Name: count, dtype: int64

In [42]:
df_clean["SEASON"].isna().sum()

np.int64(0)

### Human Impact

Features will be created for TOTAL_INJURIES and TOTAL_FATALITIES using the indirect and direct human impact columns. There will also be a feature created for ANY_HUMAN_IMPACT, do determine whether there was human impact from the event.

In [51]:
df_clean['TOTAL_INJURIES'] = (
    df_clean['INJURIES_DIRECT'] +
    df_clean['INJURIES_INDIRECT'] 
)

df_clean['TOTAL_FATALITIES'] = (
    df_clean['DEATHS_DIRECT'] +
    df_clean['DEATHS_INDIRECT']
)

df_clean['ANY_HUMAN_IMPACT'] = (
    (df_clean['TOTAL_INJURIES'] + df_clean['TOTAL_FATALITIES']) > 0
).astype(int)

In [57]:
df_clean[
    [
        "INJURIES_DIRECT",
        "INJURIES_INDIRECT",
        "TOTAL_INJURIES",
        "DEATHS_DIRECT",
        "DEATHS_INDIRECT",
        "TOTAL_FATALITIES",
        "ANY_HUMAN_IMPACT"
    ]
].head(5)

,INJURIES_DIRECT,INJURIES_INDIRECT,TOTAL_INJURIES,DEATHS_DIRECT,DEATHS_INDIRECT,TOTAL_FATALITIES,ANY_HUMAN_IMPACT
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0

### Economic Impact

Property damage and crop damage features have already been converted from string to floats. They are now PROPERTY_DAMAGE_USD and CROP_DAMAGE_USD. A new feature will now be created that describes the TOTAL_ECONOMIC_IMPACT, which will add the values of the two damage columns together. 

A feature will also be created that gives a value of 1 to any total damage that is over $100,000 and is considered MAJOR_PROPERTY_DAMAGE.

In [59]:
df_clean['TOTAL_ECONOMIC_IMPACT_USD'] = (
    df_clean['PROPERTY_DAMAGE_USD'] +
    df_clean['CROP_DAMAGE_USD']
)

In [62]:
df_clean['MAJOR_PROPERTY_DAMAGE'] = (
    df_clean['TOTAL_ECONOMIC_IMPACT_USD'] > 100000
).astype(int)

df_clean['MAJOR_PROPERTY_DAMAGE'].value_counts()

MAJOR_PROPERTY_DAMAGE
0    404159
1      6152
Name: count, dtype: int64

### Region

The variable REGION will be created. Since it is a categorical feature, it will be one hot encoded so it can be used easier for ML models.

In [69]:
region_map = {
    # Northeast
    "CONNECTICUT": "Northeast",
    "MAINE": "Northeast",
    "MASSACHUSETTS": "Northeast",
    "NEW HAMPSHIRE": "Northeast",
    "RHODE ISLAND": "Northeast",
    "VERMONT": "Northeast",
    "NEW JERSEY": "Northeast",
    "NEW YORK": "Northeast",
    "PENNSYLVANIA": "Northeast",

    # Midwest
    "ILLINOIS": "Midwest",
    "INDIANA": "Midwest",
    "MICHIGAN": "Midwest",
    "OHIO": "Midwest",
    "WISCONSIN": "Midwest",
    "IOWA": "Midwest",
    "KANSAS": "Midwest",
    "MINNESOTA": "Midwest",
    "MISSOURI": "Midwest",
    "NEBRASKA": "Midwest",
    "NORTH DAKOTA": "Midwest",
    "SOUTH DAKOTA": "Midwest",

    # South
    "DELAWARE": "South",
    "FLORIDA": "South",
    "GEORGIA": "South",
    "MARYLAND": "South",
    "NORTH CAROLINA": "South",
    "SOUTH CAROLINA": "South",
    "VIRGINIA": "South",
    "WEST VIRGINIA": "South",
    "DISTRICT OF COLUMBIA": "South",
    "ALABAMA": "South",
    "KENTUCKY": "South",
    "MISSISSIPPI": "South",
    "TENNESSEE": "South",
    "ARKANSAS": "South",
    "LOUISIANA": "South",
    "OKLAHOMA": "South",
    "TEXAS": "South",

    # West
    "ARIZONA": "West",
    "COLORADO": "West",
    "IDAHO": "West",
    "MONTANA": "West",
    "NEVADA": "West",
    "NEW MEXICO": "West",
    "UTAH": "West",
    "WYOMING": "West",
    "ALASKA": "West",
    "CALIFORNIA": "West",
    "HAWAII": "West",
    "OREGON": "West",
    "WASHINGTON": "West"
}

In [70]:
df_clean["REGION"] = df_clean["STATE"].map(region_map)

In [71]:
df_clean["REGION"].value_counts(dropna=False)

REGION
South        159257
Midwest      120218
West          70857
Northeast     39908
NaN           20071
Name: count, dtype: int64

In [72]:
df_clean[["STATE", "REGION"]].drop_duplicates().sort_values("STATE")

               STATE   REGION
63           ALABAMA    South
3410          ALASKA     West
5990  AMERICAN SAMOA      NaN
162          ARIZONA     West
512         ARKANSAS    South
...              ...      ...
66          VIRGINIA    South
406       WASHINGTON     West
61     WEST VIRGINIA    South
1336       WISCONSIN  Midwest
1315         WYOMING     West

[69 rows x 2 columns]

In [73]:
region_encoded = pd.get_dummies(
    df_clean["REGION"],
    prefix="REGION",
    dtype=int
)

df_clean = pd.concat([df_clean, region_encoded], axis=1)

In [74]:
df_clean[
    [
        "STATE",
        "REGION",
        "REGION_Northeast",
        "REGION_Midwest",
        "REGION_South",
        "REGION_West"
    ]
].head(20)

,STATE,REGION,REGION_Northeast,REGION_Midwest,REGION_South,REGION_West
0,GEORGIA,South,0,0,1,0
1,KANSAS,Midwest,0,1,0,0
2,KANSAS,Midwest,0,1,0,0
3,KANSAS,Midwest,0,1,0,0
4,KANSAS,Midwest,0,1,0,0
5,KANSAS,Midwest,0,1,0,0
6,COLORADO,West,0,0,0,1
7,COLORADO,West,0,0,0,1
8,COLORADO,West,0,0,0,1
9,KANSAS,Midwest,0,1,0,0
10,COLORADO,West,0,0,0,1
11,KANSAS,Midwest,0,1,0,0
12,KANSAS,Midwest,0,1,0,0
13,KANSAS,Midwest,0,1,0,0
14,KANSAS,Midwest,0,1,0,0
15,KANSAS,Midwest,0,1,0,0
16,KANSAS,Midwest,0,1,0,0
17,KANSAS,Midwest,0,1,0,0
18,KANSAS,Midwest,0,1,0,0
19,COLORADO,West,0,0,0,1

## 11. Save Cleaned/Engineered Dataset

In [76]:
df_clean.to_csv("NOAA_Storm_Events_Cleaned.csv", index=False)